### ISSUE TITLE
Get wiki for BetterToken Online

### ISSUE THREAD

**Issue by VonSub** [BetterToken/info_bettertoken#3]
I would like an instance of the new wiki's running for BetterToken for us to start listing some product info, calculations, etc. 
wiki.bettertoken.com
wiki2.bettertoken.com

**Comment by Pishoy** [comment]
can you send to me repo of wiki ? give to `pishoy` admin access ?

**Comment by VonSub** [comment]
@Pishoy you now have admin access.

I would need to come from this repo, there is no content yet, but we need it to be ready for us to start creating that.

**Comment by Pishoy** [comment]
can fix repo to use `src`  dir to the main repo to adapt new wiki?

**Comment by Pishoy** [comment]
done
